# Generated by Django 5.0.2 on 2024-03-16 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documentos', '0001_initial'),
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.documento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntrenamientoPuestoNomenclatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField()),
                ('nomenclatura', models.CharField(max_length=100)),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.puesto')),
                ('id_unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.unidadnegocio')),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberador', models.IntegerField()),
                ('firma', models.DateTimeField()),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.documento')),
            ],
        ),
    ]
