# Generated by Django 5.0.2 on 2024-04-26 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='liberador',
        ),
        migrations.AddField(
            model_name='firma',
            name='id_liberador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firma',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
