# Generated by Django 5.0.2 on 2024-04-28 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamiento', '0002_remove_firma_liberador_firma_id_liberador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='id_liberador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
