# Generated by Django 5.0.2 on 2024-05-06 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0014_alter_documento_comentarios_and_more'),
        ('Entrenamiento', '0003_alter_firma_firma_alter_firma_id_liberador'),
        ('Usuarios', '0008_alter_departamento_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamientopuestonomenclatura',
            name='id_unidad_negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.unidadnegocio'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='id_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='Documentos.documento'),
        ),
    ]
