# Generated by Django 5.0.2 on 2024-05-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamiento', '0004_alter_entrenamientopuestonomenclatura_id_unidad_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='fecha',
            field=models.DateTimeField(blank=True),
        ),
    ]
