# Generated by Django 5.0.2 on 2024-05-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamiento', '0005_alter_entrenamiento_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
