# Generated by Django 5.0.2 on 2024-05-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamiento', '0006_alter_entrenamiento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
