# Generated by Django 5.0.2 on 2024-03-16 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liberacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacion', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('revision', models.IntegerField()),
                ('aprobador', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('consecutivo', models.IntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('revision_plantilla', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('id_linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.linea')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclatura', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('codigo_identificacion', models.CharField(max_length=200)),
                ('intentos_descarga', models.IntegerField()),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormatosPermitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_documento', models.CharField(max_length=50)),
                ('Extencion', models.CharField(max_length=50)),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('accion', models.TextField()),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.documento')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('revisador', models.CharField(max_length=100)),
                ('aprobador', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('revision_actual', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('tipo_liberacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.liberacion')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='id_plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.plantilla'),
        ),
    ]
