# Generated by Django 5.0.2 on 2024-03-26 00:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
        ('Usuarios', '0004_alter_area_area_alter_departamento_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='revision_documento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='tipo_de_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.linea'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_finalizacion',
            field=models.DateTimeField(verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(choices=[('FORMATOS', 'FORMATOS'), ('GUIAS', 'GUIAS'), ('PROCEDIMIENTO', 'PROCEDIMIENTO'), ('AYUDA VISUAL', 'AYUDA VISUAL')], max_length=100),
        ),
    ]
