# Generated by Django 5.0.2 on 2024-03-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0003_alter_documento_consecutivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(max_length=500, upload_to='rutas/'),
        ),
    ]
