# Generated by Django 5.0.2 on 2024-03-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0004_alter_plantilla_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='aprobador',
            field=models.CharField(choices=[('Gerente de Calidad', 'Gerente de Calidad'), ('Gerente de Departamento', 'Gerente de Departamento'), ('Gerente de Planta', 'Gerente de Planta'), ('Ingeniero de Calidad', 'Ingeniero de Calidad'), ('Supervisor de Producción', 'Supervisor de Producción')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='autor',
            field=models.CharField(choices=[('Dueño del proceso o su designado', 'Dueño del proceso o su designado'), ('Ingeniero de Manufactura', 'Ingeniero de Manufactura'), ('Ingeniero de Sistemas de Gestió', 'Ingeniero de Sistemas de Gestió')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='revisador',
            field=models.CharField(choices=[('Gerente de Calidad', 'Gerente de Calidad'), ('Ingeniero de Calidad', 'Ingeniero de Calidad'), ('Ingeniero de Sistemas de Gestión', 'Ingeniero de Sistemas de Gestión'), ('Supervisor de Producción', 'Supervisor de Producción')], max_length=50),
        ),
    ]
