# Generated by Django 5.0.2 on 2024-04-07 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0005_alter_plantilla_aprobador_alter_plantilla_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='revision_plantilla',
        ),
        migrations.AlterField(
            model_name='documento',
            name='comentarios',
            field=models.TextField(default='Documento dado de alta manualmente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(default='APROBADO', max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_finalizacion',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='formatospermitidos',
            name='Extencion',
            field=models.CharField(choices=[('.ppt', '.ppt (PowerPoint)'), ('.pptx', '.pptx (PowerPoint)'), ('.xls', '.xls (Excel)'), ('.xlsx', '.xlsx (Excel)'), ('.doc', '.doc (Word)'), ('.docx', '.docx (Word)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='estado',
            field=models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('INHABILITADO', 'INHABILITADO')], max_length=20),
        ),
    ]
