# Generated by Django 5.0.2 on 2024-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0009_documento_revision_de_plantilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='extension',
            field=models.CharField(default='.docx', max_length=10),
        ),
    ]
