# Generated by Django 5.0.2 on 2024-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0010_alter_documento_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(max_length=500, null=True, upload_to='rutas/'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='autor',
            field=models.CharField(choices=[('Dueño del proceso o su designado', 'Dueño del proceso o su designado'), ('Ingeniero de Manufactura', 'Ingeniero de Manufactura'), ('Ingeniero de Sistemas de Gestión', 'Ingeniero de Sistemas de Gestión')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(choices=[('FORMATOS', 'FORMATOS'), ('GUIAS', 'GUIAS'), ('PROCEDIMIENTO', 'PROCEDIMIENTO'), ('AYUDA VISUAL', 'AYUDA VISUAL'), ('PLANTILLA', 'PLANTILLA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='tipo_de_area',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
