# Generated by Django 5.0.2 on 2024-04-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0011_alter_plantilla_archivo_alter_plantilla_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='rutas/'),
        ),
    ]
