# Generated by Django 5.0.2 on 2024-04-28 00:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0013_alter_documentobloqueado_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='comentarios',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
