# Generated by Django 5.0.2 on 2024-03-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_perfilusuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(choices=[('Area 1', 'Area 1'), ('Area 2', 'Area 2'), ('Area 3', 'Area 3'), ('Area 4', 'Area 4')], max_length=100),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(choices=[('Calidad', 'Calidad'), ('Produccion', 'Produccion'), ('Almacen', 'Almancen'), ('Planeacion', 'Planeacion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='tipo',
            field=models.CharField(choices=[('DIRECTO', 'DIRECTO'), ('INDIRECTO', 'INDIRECTO')], max_length=40),
        ),
    ]
