# Generated by Django 5.0.2 on 2024-04-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_linea_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(choices=[('Area 1', 'Area 1'), ('Area 2', 'Area 2'), ('Area 3', 'Area 3'), ('Area 4', 'Area 4'), ('Departamento', 'Departamento')], max_length=100),
        ),
    ]
