# Generated by Django 5.0.2 on 2024-04-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_alter_area_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(choices=[('Calidad', 'Calidad'), ('Produccion', 'Produccion'), ('Almacen', 'Almancen'), ('Planeacion', 'Planeacion')], max_length=200),
        ),
    ]
