# Generated by Django 5.0.2 on 2024-05-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_alter_departamento_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(choices=[('Calidad', 'Calidad'), ('Produccion', 'Produccion'), ('Almacen', 'Almacen'), ('Planeacion', 'Planeacion'), ('Entrenamiento', 'Entrenamiento')], max_length=200),
        ),
        migrations.AlterField(
            model_name='unidadnegocio',
            name='gerente_Calidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadnegocio',
            name='gerente_ingenieria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadnegocio',
            name='gerente_produccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
