# Generated by Django 5.0.2 on 2024-05-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_alter_departamento_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='por_unidad_negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.unidadnegocio'),
        ),
    ]
